apiVersion: v1
kind: Service
metadata:
  name: hello-world-app-service
spec:
  type: LoadBalancer
  selector:
    app: hello-world-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
