apiVersion: v1
kind: Service
metadata:
  name: flask-app-service # Change this to a descriptive name if needed
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
