apiVersion: v1
kind: Service
metadata:
  name: kubernetes # Change this to a descriptive name if needed
spec:
  type: LoadBalancer
  selector:
    app: flask-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80